### PR TITLE
SEC: pytreasurydirect.py: http -> https

### PR DESCRIPTION
**Pull request by westurner**

### CODE REVIEW

**Comment by npezolano** [comment]
Thanks! looks good!

**Comment by westurner** [comment]
Thanks!

Are there any plans to release a new version to PyPI?

**Comment by npezolano** [comment]
Sure I can put a release out tonight or tomorrow.

**Comment by westurner** [comment]
Great. Thanks again!

**Comment by npezolano** [comment]
New version is up on pypi

**Pull request merged**
